name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Install Python dependencies
      run: bash setup.sh
    
    - name: Run test_treegen
      run: |
        bash test_treegen.sh
        if [ $? -ne 0 ]; then
          echo "test_treegen failed"
          exit 1
        fi
    
    - name: Run test_codegen
      run: |
        python3 -m tests.test_codegen --num-tests 3 --max-trees 3 --max-depth 2
        if [ $? -ne 0 ]; then
          echo "test_codegen failed"
          exit 1
        fi