name: Test CodeGen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-codegen:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Install Python dependencies
      run: bash setup.sh
    
    - name: Setup C++ build environment
      run: |
        cd src/cpp_code
        rm -rf benchmark
        bash build_benchmark.sh
        cd ../..
    
    - name: Run test_codegen
      run: |
        python3 -m tests.test_codegen
        if [ $? -ne 0 ]; then
          echo "test_codegen failed"
          exit 1
        fi